# Generated by Django 3.0.6 on 2020-05-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posto', models.CharField(max_length=2)),
                ('nome', models.CharField(max_length=255)),
                ('numero_ordem', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=15)),
                ('upag', models.CharField(max_length=50)),
                ('sub_om', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo', models.DateField()),
            ],
        ),
    ]
